import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-slate-900 text-white ">
        <Toaster
          position="bottom-right"
          duration={2500}
          toastOptions={{
            style: {
              background: "#0f172b",
              color: "#fff",
              borderColor: "rgba(255,255,255,0.5)",
            },
          }}
        />
        {children}
      </body>
    </html>
  );
}
